{% set version = "0.0.16" %}
{% set python_min = "3.10" %}

package:
  name: lsp-tree-sitter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lsp-tree-sitter/lsp_tree_sitter-{{ version }}.tar.gz
  sha256: 6e11d66629ed31b4c829ee87a6669468a6a952b9e84b56e5898234e6a599cf62

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
  run:
    - python >={{ python_min }}
    - colorama
    - jinja2
    - jsonschema >=4.0.0
    - pygls
    - tree_sitter >=0.22.0

test:
  commands:
    - pip check
  imports:
    - lsp_tree_sitter
  requires:
    - pip
    - python ={{ python_min }}

about:
  dev_url: https://github.com/neomutt/lsp-tree-sitter
  home: https://github.com/neomutt/lsp-tree-sitter
  summary: A library to create language servers
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - template/LICENSE

extra:
  recipe-maintainers:
    - danielnachun
